name: Accuracy cchcker

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --no-deps openvino openvino_dev -r ci/requirements-openvino-dev.txt -r ci/requirements-downloader.txt -r ci/requirements-conversion.txt -r ci/requirements-quantization.txt
    - name: Test with pytest
      run: |
        python -m pytest tools/accuracy_checker
