name: model_api-github-actions
on: pull_request
permissions: read-all  # Required by https://github.com/ossf/scorecard/blob/e23b8ad91fd6a64a0a971ca4fc0a4d1650725615/docs/checks.md#token-permissions
jobs:
  model_api-github-actions:
    strategy:
      matrix:
        runs-on: [ubuntu-20.04, ubuntu-22.04]
        python-version: [3.7, 3.8, 3.9, '3.10', '3.11']
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install demos/common/python/ openvino
      - run: python -c "from model_zoo import model_api"
